version: ~> 1.0
os: linux
language: python
# Support Ubuntu/Python version combinations are documented on
# https://docs.travis-ci.com/user/languages/python/#python-versions
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

matrix:
  allow_failures:
    - python: 3.9-dev  # allow tests to fail with this pre-release of Python

install: pip install tox-travis
script: tox
